Bump SDK to v15 in token_manager
PolymathNetwork/technical-content-examples pull request #4
Opened 2022-07-14 09:05 UTC by prashantasdeveloper

2022-07-14 15:33 UTC, polymath-eric requested changes

2022-07-20 09:42 UTC, prashantasdeveloper commented on token_manager/pages/index.tsx
> +    // const toAdd: AddInvestorUniquenessClaimParams = Object.assign(
Fixed this

2022-07-20 09:43 UTC, prashantasdeveloper commented on token_manager/pages/index.tsx
> +    // await setAsset(asset);
Removed this. After transfer ownership authorizations now needed to be refreshed.

2022-07-20 13:15 UTC, polymath-eric approved these changes

2022-07-21 12:16 UTC, VictorVicente approved these changes

2022-07-21 12:17 UTC, merged